# Generated by Django 5.1.1 on 2024-09-30 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_todo_nomealugou_todo_telefonealugou_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="todo",
            new_name="livros",
        ),
    ]
