# Generated by Django 5.1.1 on 2024-09-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0003_rename_todo_livros"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="livros",
            options={"ordering": ["titulo"]},
        ),
        migrations.AlterField(
            model_name="livros",
            name="anoPublicacao",
            field=models.DateField(verbose_name="Ano de Publicação"),
        ),
        migrations.AlterField(
            model_name="livros",
            name="autor",
            field=models.CharField(max_length=100, verbose_name="Autor"),
        ),
        migrations.AlterField(
            model_name="livros",
            name="dataAlugou",
            field=models.DateField(null=True, verbose_name="Data do Aluguel"),
        ),
        migrations.AlterField(
            model_name="livros",
            name="genero",
            field=models.CharField(max_length=100, verbose_name="Gênero"),
        ),
        migrations.AlterField(
            model_name="livros",
            name="nomeAlugou",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Nome do Locador"
            ),
        ),
        migrations.AlterField(
            model_name="livros",
            name="telefoneAlugou",
            field=models.IntegerField(
                max_length=11, null=True, verbose_name="Telefone do Locador"
            ),
        ),
        migrations.AlterField(
            model_name="livros",
            name="titulo",
            field=models.CharField(max_length=100, verbose_name="Título"),
        ),
    ]
